<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_50 Cash</name>
   <tag></tag>
   <elementGuidId>61d18bae-0fd1-4810-8539-d8f792ebcd1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='$50 Cash']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_V2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;$50 Cash&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a50411e-58dc-493a-b6a1-bf851ffce67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_V2</value>
      <webElementGuid>2db9983a-d0de-473a-bfbe-db2bde1ea9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>de06fa4c-5d95-4cbb-a2a9-13f267bfa700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$50 Cash</value>
      <webElementGuid>fa762437-991e-49c9-9165-4fafcf496490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_V2&quot;)</value>
      <webElementGuid>db19b186-1fdf-43f1-853d-76474a95e289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_V2']</value>
      <webElementGuid>ee3d86ec-3dd8-467e-ae05-020d3cc4c716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_V3']/table/tbody/tr/td/div</value>
      <webElementGuid>7ec0e506-31ee-4ef6-b512-a1a93495f136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$20 Cash'])[1]/following::div[2]</value>
      <webElementGuid>c8860ae0-08ff-43fd-924f-8e115eb510ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$10 Cash'])[1]/following::div[4]</value>
      <webElementGuid>f42e440d-9907-4528-88aa-eae87c801690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100 Cash'])[1]/preceding::div[1]</value>
      <webElementGuid>888e3ee3-98bb-48d6-99fa-dc32abc778a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EFTPOS'])[1]/preceding::div[3]</value>
      <webElementGuid>c79ddf52-35f7-4b80-be73-f903b00b7dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$50 Cash']/parent::*</value>
      <webElementGuid>d468c1f1-4fa2-448c-afc4-57a24aed0fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[4]/table/tbody/tr/td/div</value>
      <webElementGuid>1f5f06ac-d4b7-4686-b623-ce14f85f9881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_V2' and (text() = '$50 Cash' or . = '$50 Cash')]</value>
      <webElementGuid>b8c89a63-cf95-4da4-bd03-fb30e766d589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
