<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ACCOUNT (A)</name>
   <tag></tag>
   <elementGuidId>2b58dc71-aba0-4c9a-9727-cbd011e6139e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_B0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='ACCOUNT (']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;ACCOUNT (A)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e0ad395-76e2-48c1-a5a6-d45bafbdf0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_B0</value>
      <webElementGuid>7d53f37f-164f-4469-b246-b4ba79fc6497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3bb11011-0390-481d-902a-b09af5177225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCOUNT (A)</value>
      <webElementGuid>2fd2c7ad-f4f6-46cb-b48e-9c7ea21e4fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_B0&quot;)</value>
      <webElementGuid>734eb1d2-c588-4b4d-b7ac-7b55de36163f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_B0']</value>
      <webElementGuid>50c03f43-3fb4-4464-b556-3ef0eb61ff3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_B1']/table/tbody/tr/td/div</value>
      <webElementGuid>d9889952-1149-4c35-9461-8c15dc035df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$14.93'])[1]/following::div[2]</value>
      <webElementGuid>39700cce-c2f5-4462-9dd5-ae9e78f52811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total INC'])[1]/following::div[3]</value>
      <webElementGuid>8a7e0dd0-826f-404e-b437-04e12ea4acb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCOUNT (']/parent::*</value>
      <webElementGuid>1ebcd602-1c1f-497c-b4c2-8427f0421f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>4bd6097f-9710-4003-abad-25112e5934e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_B0' and (text() = 'ACCOUNT (A)' or . = 'ACCOUNT (A)')]</value>
      <webElementGuid>fa34c2da-e533-4dc0-a65f-f117193e26c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
