<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Tally Maintenance</name>
   <tag></tag>
   <elementGuidId>815a8963-54c5-4c90-8463-bb7130feb57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.windowHeaderText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Tally Maintenance']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Tally Maintenance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1024bf3c-0c4e-432c-a0d8-e5d1e4dd3f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da4c4ca6-7785-487b-9970-8d80fc71ae11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>windowHeaderText</value>
      <webElementGuid>6ad8b439-8c74-4414-8d13-6ab8668b3df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>738290a8-b188-47e9-8bff-b3d5d211b5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>95e2cab9-9da3-4c75-9506-c968d1ed9ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tally Maintenance</value>
      <webElementGuid>4cb4fc8d-ca18-46d9-a76c-7ad0310bf389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_OV&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;windowHeaderText&quot;]</value>
      <webElementGuid>19898748-09a1-4ecd-bc0f-5669821a904b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_OV']/table/tbody/tr/td</value>
      <webElementGuid>684af259-8e4f-4286-8b8a-eed189b05d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LM'])[1]/following::td[13]</value>
      <webElementGuid>77c35606-1bd6-40fb-873c-bafc838ea012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Length'])[1]/following::td[14]</value>
      <webElementGuid>b8e5dada-aa24-4119-a4a3-fc223e903e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tally Maintenance'])[2]/preceding::td[1]</value>
      <webElementGuid>e4addc68-8691-4a37-8972-ffee86e1fedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tally Maintenance']/parent::*</value>
      <webElementGuid>9a91776a-486e-49c9-be36-9c909231ac4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/table/tbody/tr/td</value>
      <webElementGuid>d3b96f08-688b-4d20-978c-df417dd68960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Tally Maintenance' or . = 'Tally Maintenance')]</value>
      <webElementGuid>a19d382f-3755-4205-9549-44d723084ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
