<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_m_customerIdX</name>
   <tag></tag>
   <elementGuidId>6f55511f-3a9f-4a03-b7e7-f2ddd729a78d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_8M</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_8M']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Customer&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93b48174-f21a-4d42-b0ad-989de3c50c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f16bfedf-6890-42df-a54b-e9853ed02454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerIdX</value>
      <webElementGuid>1bcd8dd3-3aaf-430f-8db2-78b9dbdab953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_8M</value>
      <webElementGuid>2db4dd71-71de-49b4-a711-634995ce7951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24dab1a0-ab9b-44b7-8004-34ada5809554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_0</value>
      <webElementGuid>9e9197c3-b624-44a6-9565-8bc844531198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>80cb419f-ffd1-4950-82ac-4f5ab4ca316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9b4f174-f069-4b3a-815e-f78d4fea870f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_0._handleInput()</value>
      <webElementGuid>42acdd3c-1942-4b6e-bf6a-bd839163fef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_ComboBoxItem_0 == null) return;isc_ComboBoxItem_0.$1162()</value>
      <webElementGuid>268e1c43-ae43-42b7-b634-3962b22cb6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>02209491-b903-4483-bbea-4a9b774a3d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSuggestBoxFocused</value>
      <webElementGuid>4c7f7791-1247-4191-955e-d15b1e6d4a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2394</value>
      <webElementGuid>6af9bca7-5f42-45b4-bb61-af180875efc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_8M&quot;)</value>
      <webElementGuid>1260f0ba-b393-459a-a810-6eb91e2aaabc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_8M']</value>
      <webElementGuid>cf9ed98a-c7f7-49b6-a7b5-ebba189c3ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_HL']/input</value>
      <webElementGuid>e98bbb28-d4d6-4976-ba17-2bb8f4f85832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e75384cc-fa97-41a2-b55e-71aa8bbf962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'customerIdX' and @id = 'isc_8M']</value>
      <webElementGuid>ef4b571f-3c72-47bb-ad0b-d499b6e452ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
