<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_tablevalue1</name>
   <tag></tag>
   <elementGuidId>064bcf27-5039-49f0-aa08-c79b499f02db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/table/tbody/tr[1]/td[1]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.cellSelectedOver > div > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;20137895&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e308eb3-71ec-44ad-98db-5537c9c33757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>2b297b48-8441-4c1d-b785-f2a74de8e27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>20e393b9-9870-4fe6-928f-7895f86ae09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.customerView_Invoices__Orders__Quotes__Projects___Jobs_ttInvoice_ListGrid1) return customerView_Invoices__Orders__Quotes__Projects___Jobs_ttInvoice_ListGrid1.$30i(event,0,0);</value>
      <webElementGuid>30bc20b2-4061-4fd8-8aa0-cbddc140b1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20137895</value>
      <webElementGuid>fc47c965-f3f0-4a51-b051-47cd5f29ad56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_19Stable&quot;)/tbody[1]/tr[1]/td[@class=&quot;cellSelectedOver&quot;]/div[1]/a[1]</value>
      <webElementGuid>2da9528f-e876-4e8d-ad9c-f3b003ce2e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(window.customerView_Invoices__Orders__Quotes__Projects___Jobs_ttInvoice_ListGrid1) return customerView_Invoices__Orders__Quotes__Projects___Jobs_ttInvoice_ListGrid1.$30i(event,0,0);']</value>
      <webElementGuid>3d77e2b0-6bce-48ad-a211-07c42d1c61ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_19Stable']/tbody/tr/td/div/a</value>
      <webElementGuid>a9de472f-9524-4dd6-a00c-f0a99d12c4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'20137895')]</value>
      <webElementGuid>33fcaf94-5998-4b8d-a715-745e513561f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$87.46'])[1]/following::a[1]</value>
      <webElementGuid>75ecab8b-f100-4ca1-b041-1a04632efaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sett. ExpDate'])[1]/following::a[1]</value>
      <webElementGuid>121fdb28-9a83-46ac-97d7-9537e6565306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POS Pickup'])[1]/preceding::a[2]</value>
      <webElementGuid>da59149f-3269-4158-8135-0b5f89f158c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$43.73'])[1]/preceding::a[2]</value>
      <webElementGuid>c81a1e86-1854-4820-b7ac-2282a91cb6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20137895']/parent::*</value>
      <webElementGuid>863d6212-3242-45a3-bcc4-4a377ec25cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void')])[16]</value>
      <webElementGuid>1a45bd16-373a-439f-a979-a3d4bedc2b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>f423c960-bbd5-4463-bc8c-d7cd3918873d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void' and (text() = '20137895' or . = '20137895')]</value>
      <webElementGuid>931264f0-1813-4d35-a472-a92d857a4972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
