<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ACCOUNT (A)</name>
   <tag></tag>
   <elementGuidId>073659ff-4cc9-4d12-83a9-f1106eff5480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='ACCOUNT (']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_AU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;ACCOUNT (A)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02192c97-af82-4484-8b0a-8b5007536939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_AU</value>
      <webElementGuid>ea6c110a-c959-4e2b-abeb-2ecbfb8a9b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d1d9fb0e-d665-46f8-8faa-39ed03e93915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCOUNT (A)</value>
      <webElementGuid>1f3a56e2-1b16-43eb-8779-daf905024c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_AU&quot;)</value>
      <webElementGuid>315ece8a-bdd6-4a36-8501-a80779828453</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_AU']</value>
      <webElementGuid>9f461f27-28f8-4cf2-9cc6-8c4590ae65ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_AV']/table/tbody/tr/td/div</value>
      <webElementGuid>d02dc14b-4e23-40eb-a843-4e214cb6db7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$43.73'])[1]/following::div[2]</value>
      <webElementGuid>8bd9bb56-9970-4902-83b3-713d1696d563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total INC'])[1]/following::div[3]</value>
      <webElementGuid>62eaceee-41b5-4c86-80ae-98c7631cc90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCOUNT (']/parent::*</value>
      <webElementGuid>17259028-6aa0-4bce-bc98-ab3ce6323239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>481d649a-f303-4244-8ab5-c1f3025b2375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_AU' and (text() = 'ACCOUNT (A)' or . = 'ACCOUNT (A)')]</value>
      <webElementGuid>b7c26f48-6fa9-42ed-86c6-cbd8a450e4c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
