<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_invoiceNum</name>
   <tag></tag>
   <elementGuidId>ce5aec44-4336-4ddc-b052-4712ef6e1304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/form/table/tbody/tr[2]/td[1]/div[@class = 'headerItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_8H</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;20137898&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0f21be5-98e5-486b-95ae-d527c1f00be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_8H</value>
      <webElementGuid>088dd85c-ad24-4139-aa83-901337eda6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_HeaderItem_0</value>
      <webElementGuid>d6235bca-cf80-4eca-a8e5-f0b27d59ac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>d8bd42f2-d276-4d03-a0e5-531a9d7c695b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerItem</value>
      <webElementGuid>a6f956d6-04ef-4aea-b424-1332e6790d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20137898</value>
      <webElementGuid>8c73c377-9456-4dfa-81c8-65a1e17d331d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_8H&quot;)</value>
      <webElementGuid>e56def03-5682-4c14-903f-5db7376d78c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_8H']</value>
      <webElementGuid>f05e97e6-c350-4436-869d-ffd03ca54013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_8G']/div</value>
      <webElementGuid>07cc95a8-7b41-40de-9dee-82bdae9b140e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/following::div[7]</value>
      <webElementGuid>8951abf7-1561-4b98-8724-b331880de1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='m'])[1]/preceding::div[6]</value>
      <webElementGuid>2f765706-fc64-4baa-ab68-8a5846fe1bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20137898']/parent::*</value>
      <webElementGuid>f1e991aa-891c-4b0d-8d2a-a4ab2b7704ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/table/tbody/tr[2]/td[1]/div[@class = 'headerItem']</value>
      <webElementGuid>469ffe95-889f-41b7-b0ad-a914f5c82380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_8H' and (text() = '20137898' or . = '20137898')]</value>
      <webElementGuid>c8b85dad-3c29-4597-a5f9-58c8e12d898e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
