<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Point Of Sale</name>
   <tag></tag>
   <elementGuidId>28aefbfe-c571-4cd8-9576-0231927baf6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_MenuPopout_2_0_valueCell2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_MenuPopout_2_0_valueCell2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Point Of Sale&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ea078766-3a2d-4cbd-ae18-deb2e7db0e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_MenuPopout_2_0_valueCell2</value>
      <webElementGuid>4ab75e05-325e-4aa0-a943-1eb72b29c6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeCellSelectedOver</value>
      <webElementGuid>0d124d89-325f-4538-8c3d-1b997d7ff749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Point Of Sale</value>
      <webElementGuid>859c6de5-0a8a-4785-ad71-7d0608054e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MenuPopout_2_0_valueCell2&quot;)</value>
      <webElementGuid>a478aadf-39dd-4728-905e-0e458bf67424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_MenuPopout_2_0_valueCell2']</value>
      <webElementGuid>0f93cae7-5dee-4038-9376-344fb47704e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Ctable']/tbody/tr[3]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>585e6eb9-df98-4614-a292-829b8615847b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Processing'])[1]/following::td[4]</value>
      <webElementGuid>6f9f423a-279e-4dfc-add9-62387735ed6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::td[8]</value>
      <webElementGuid>381e04eb-e5fc-4b21-829a-c31ba650880d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/preceding::td[3]</value>
      <webElementGuid>bd75ad4b-09cb-4bd9-b54c-53967d0ea113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Orders'])[1]/preceding::td[7]</value>
      <webElementGuid>48cbbfae-3882-4e11-b1cc-d4fd5c8a0408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Point Of Sale']/parent::*</value>
      <webElementGuid>9005af8c-d466-421e-ace6-e8debb2f1ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>d4c9efdc-dd0f-4867-9675-38ad7b183d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_MenuPopout_2_0_valueCell2' and (text() = 'Point Of Sale' or . = 'Point Of Sale')]</value>
      <webElementGuid>98ac19a4-9130-4750-998d-e5c7098af9ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
