<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tally MaintenanceTally Maintenance</name>
   <tag></tag>
   <elementGuidId>9c535129-689f-4a4e-8b54-4c17c7f82c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_NE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_NE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tally MaintenanceTally Maintenance&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>204e9cc0-c713-457e-a2e6-aac6f8df7310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_NE</value>
      <webElementGuid>fd3d14b3-8733-489f-944d-f9ef09f90dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>isc_Window_1_headerLabelLayout</value>
      <webElementGuid>cf23dbe8-bc53-4957-a74a-b17fb66b4e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>daca2385-4bf8-42dd-bdc7-a1c863b3f58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return isc_Window_1_headerLabelLayout.$lh()</value>
      <webElementGuid>02ee74e6-4137-499c-8d7f-73c9ba74f38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5cbc5047-3913-4772-95bd-a991f17e249e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tally MaintenanceTally Maintenance</value>
      <webElementGuid>a187d8d0-ca8a-44ba-a070-5066d82038a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_NE&quot;)</value>
      <webElementGuid>6cea432c-64cd-442b-9c1b-1ad75fb45bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_NE']</value>
      <webElementGuid>c4067c3c-cbde-4986-b386-8cdd2630f823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_ND']/div</value>
      <webElementGuid>ffeb8b5c-1342-4263-b265-e07b4cc77a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LM'])[1]/following::div[31]</value>
      <webElementGuid>85231bba-0043-4d58-912d-e953bd3f0835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Length'])[1]/following::div[35]</value>
      <webElementGuid>461c671d-61c4-4067-a689-fc8d2b048273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>1778d46c-b8f4-46ed-a3a1-79deb6f5a7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_NE' and (text() = ' Tally MaintenanceTally Maintenance' or . = ' Tally MaintenanceTally Maintenance')]</value>
      <webElementGuid>ad4da515-50ab-4315-9d03-e29f3ed18511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
