<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_add</name>
   <tag></tag>
   <elementGuidId>7be1ef7c-871a-470e-9800-91f6fd4f153a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_G9 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='isc_G9']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_EY >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a5379e7b-a910-4b09-b66c-9ef5cbc708c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks/images/custom/menus/checkmark-circle.png</value>
      <webElementGuid>b7ed9237-c9c0-4f60-a7d5-b8f1c649416f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>119f1ddd-d256-4919-9fa2-a7b9a1b7560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ed39ec1f-b446-4022-a1e4-749ceef0595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e41e13d8-562f-4d3f-9953-c3032df8dd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_G9&quot;)/img[1]</value>
      <webElementGuid>8b301c5b-0659-4d6d-beb1-3ffce73f5140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='isc_G9']/img</value>
      <webElementGuid>a5d21c78-86c3-43e2-af95-c8361b65db9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks/images/custom/menus/checkmark-circle.png')]</value>
      <webElementGuid>0c126285-4447-4c3b-9234-5f664ab37e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/a/img</value>
      <webElementGuid>9ff1cda5-01b6-4628-87fa-091fa19a59b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.dahlsens.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks/images/custom/menus/checkmark-circle.png']</value>
      <webElementGuid>69a06e44-a6a0-417c-b338-cb3fb47db61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
