<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_P_prodId</name>
   <tag></tag>
   <elementGuidId>f3f2bf78-7f9a-4b8c-9626-b75d2cb7db58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_QP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div[3]/div/div/div/div/div[2]/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/input[@type = 'TEXT' and @name = 'prodId']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'TEXT' and @name = 'prodId' and @id = 'isc_QP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7757303a-327a-4d9d-b4d1-d0b365abd5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>c3520cd3-0b5e-4679-b1ee-53362c5a5fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prodId</value>
      <webElementGuid>16ee0fc2-e54c-4208-b644-0a4cefb2248a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_QP</value>
      <webElementGuid>d6111db0-086b-41bc-ae7d-d2f790fada2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af36ed19-2e27-4f89-900a-fdcd4a74977b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_34</value>
      <webElementGuid>05873df0-62e1-4743-8d3e-760e08504941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>4abfa4da-13f5-4956-8fc4-897f702f54ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4421ecab-4c27-4f22-9893-c0e9f8750d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_34._handleInput()</value>
      <webElementGuid>d199a433-b459-4b8c-987a-c39f813964ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_34 == null) return;isc_TextItem_34.$1162()</value>
      <webElementGuid>633cdc0d-f180-4474-8098-d19a4f0e2563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>b6bf252e-f59d-4b2d-be35-15bbdc787488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItemFocused</value>
      <webElementGuid>1eb7ae02-1fca-4e6a-81a5-3cb17889c386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3769</value>
      <webElementGuid>c97c3ed4-3812-4c98-ac17-d5179b7842bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_QP&quot;)</value>
      <webElementGuid>b6cb2d50-6a30-4911-a336-d2f86dc41395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_QP']</value>
      <webElementGuid>2f823357-cb71-4ba7-8d01-1ef3e32d1a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_TZ']/tbody/tr/td/input</value>
      <webElementGuid>472862ab-17e3-44df-b2be-ca419600ceb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/div/div[2]/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/input[@type = 'TEXT' and @name = 'prodId' and @id = 'isc_QP']</value>
      <webElementGuid>e228a894-739f-4801-b3d6-ce691e031d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'prodId' and @id = 'isc_QP']</value>
      <webElementGuid>f6263973-a1fe-43f2-8e74-1feb75c2f4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_EC']</value>
      <webElementGuid>4e65bee3-121e-4550-8568-eb7cd73e52bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_HM']/tbody/tr/td/input</value>
      <webElementGuid>efe751d9-ff64-4e53-8fc0-1b779ed66c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/div/div[2]/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>3175943b-72c7-44de-96d9-31a3b0f4a3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'prodId' and @id = 'isc_EC']</value>
      <webElementGuid>744c3f0b-49fa-4f1e-9a19-c66722d7a973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
