<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity_quantityOrdered</name>
   <tag></tag>
   <elementGuidId>eacffe12-0a65-4bcb-845d-aea2de261800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_EG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/form/table/tbody/tr[2]/td[2]/input[@type = 'TEXT' and @name = 'quantityOrdered']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Quantity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db4d0d1e-46d2-4958-bf48-02f583b57fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>e5acfb5e-284b-4c33-b70d-c7822cd0eb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantityOrdered</value>
      <webElementGuid>82d86765-3521-40aa-843f-bbee040e3265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_EG</value>
      <webElementGuid>f694cf02-02d0-4919-bf7f-7c3f3d7b35e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>386e97f2-aa9b-4fcf-b7cd-7bba4203cef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_13</value>
      <webElementGuid>25d8204b-a2f9-4b6f-bed9-2c9d15193156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>90e5b899-2c0a-43a4-a8d8-3e1471fd5a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a0e2a89-1f28-4d9f-a2d1-d71daa8b1ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_13._handleInput()</value>
      <webElementGuid>d683718f-915d-4e5a-8d86-ff748b1a4dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_13 == null) return;isc_TextItem_13.$1162()</value>
      <webElementGuid>51f71181-fe0c-4386-9950-c6d9a5696dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>99a577fa-b5b3-48ee-a595-c70701bdd00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItemFocused</value>
      <webElementGuid>632f890e-c6ea-490c-b1fb-8b4e769d6c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3791</value>
      <webElementGuid>e82e817d-66de-402c-b249-8c8155afdcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_EG&quot;)</value>
      <webElementGuid>8741af23-cf04-4618-a3eb-d220983ce811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_EG']</value>
      <webElementGuid>30542cad-5be0-443e-9a79-404113e38f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_EE']/input</value>
      <webElementGuid>37e69628-bcfa-4431-98cb-38368e6c241b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>0f0116a2-780b-4504-85d4-9a66ba291364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'quantityOrdered' and @id = 'isc_EG']</value>
      <webElementGuid>522d34ed-ab9d-46e3-a176-71a50fb3dba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
