<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Purchase_Orders_level3</name>
   <tag></tag>
   <elementGuidId>7a507987-d713-44e8-addf-ede2959d238b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_MenuPopout_2_0_valueCell16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_MenuPopout_2_0_valueCell16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Purchase Orders&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c9dc760b-bb7d-4ece-a072-d31bda50fbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_MenuPopout_2_0_valueCell16</value>
      <webElementGuid>e77f772b-19ad-441f-ba40-3fdde0d29e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeCellSelectedOver</value>
      <webElementGuid>69f5fec8-db53-464a-98e3-15fa99961e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>c0732de1-a7f1-47de-89a2-f984b49a41af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MenuPopout_2_0_valueCell16&quot;)</value>
      <webElementGuid>2475f0a0-888f-4a13-af6c-a65205feed5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_MenuPopout_2_0_valueCell16']</value>
      <webElementGuid>fb3cce4d-ca70-487c-89a5-cd44f10be4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_6Atable']/tbody/tr[17]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>f9b3e41e-dea0-413f-8060-e01ce272da9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Requisitions'])[1]/following::td[4]</value>
      <webElementGuid>92f13fc7-4ece-489e-9ba8-8ba00cfd68cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Processing'])[2]/following::td[8]</value>
      <webElementGuid>3181caf5-0b31-4748-bdbb-582e899065c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Receipting'])[1]/preceding::td[3]</value>
      <webElementGuid>0e555f7b-f594-4f1b-beb7-9b634104e3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Transfers'])[1]/preceding::td[7]</value>
      <webElementGuid>3d660c4a-b72b-4908-a9b2-65b2bc11a8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchase Orders']/parent::*</value>
      <webElementGuid>80d686ad-93ea-4f92-b70a-1ed8b0e2d704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>acdee145-47ab-42d9-bf17-6fe08258918c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_MenuPopout_2_0_valueCell16' and (text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      <webElementGuid>c3092178-fad3-4bca-8984-2f1a69c5af1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
