<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Purchasing_Receipting_level1</name>
   <tag></tag>
   <elementGuidId>c9309449-2058-41c9-b3da-3a2c260fc687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_MenuPopout_2_0_valueCell13']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_MenuPopout_2_0_valueCell13 > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Purchasing &amp; Receipting&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>612dd55d-a2ee-4e9b-90dc-cd1d921bfeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchasing &amp; Receipting</value>
      <webElementGuid>c77721a7-535d-4b40-8798-279a5611d619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MenuPopout_2_0_valueCell13&quot;)/b[1]</value>
      <webElementGuid>7efe9060-174b-4441-bc2b-d35fffafc103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_MenuPopout_2_0_valueCell13']/b</value>
      <webElementGuid>c509ab9e-fab5-4db9-89c5-a94e72b3d567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkOrders'])[1]/following::b[1]</value>
      <webElementGuid>ca892127-137a-41bb-b8aa-5528dfe6bf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/following::b[2]</value>
      <webElementGuid>7a8e127e-35b0-4361-bc7d-468fac53b5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Pricing'])[1]/preceding::b[2]</value>
      <webElementGuid>2a22e6b2-b15c-469a-b971-3b78efb61596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Ledger'])[1]/preceding::b[4]</value>
      <webElementGuid>5a0016fc-d1ed-4dab-b0f3-03b88979bf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchasing &amp; Receipting']/parent::*</value>
      <webElementGuid>b9ce6b83-35c5-4a17-99cf-295d1b19211b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td/div/table/tbody/tr/td[3]/b</value>
      <webElementGuid>022cc915-368a-4159-a792-fa586b914fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Purchasing &amp; Receipting' or . = 'Purchasing &amp; Receipting')]</value>
      <webElementGuid>05b206d3-1294-40c7-b9de-0e9cb3dd2537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
