<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1</name>
   <tag></tag>
   <elementGuidId>b9eee0f4-739f-47ac-bec5-9a884a36a34b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='if(window.suppDeliveryAddressesFind_results_ListGrid1) return suppDeliveryAddressesFind_results_ListGrid1.$30i(event,0,0);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.cellSelectedOver > div > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14d262b7-b32f-4430-b828-396005fcde33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>92b49bdf-ebce-4996-9e9b-72e62f72af65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>bfcd613d-92f4-49a2-b04e-d3da6fd6f24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.suppDeliveryAddressesFind_results_ListGrid1) return suppDeliveryAddressesFind_results_ListGrid1.$30i(event,0,0);</value>
      <webElementGuid>5a7d1060-b668-43d2-b411-526452a9731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>67147c39-c9ee-4d9c-9f9a-e7ad2528ee87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_16Ptable&quot;)/tbody[1]/tr[1]/td[@class=&quot;cellSelectedOver&quot;]/div[1]/a[1]</value>
      <webElementGuid>308951ec-9e46-4a65-8fd1-85b82944e6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(window.suppDeliveryAddressesFind_results_ListGrid1) return suppDeliveryAddressesFind_results_ListGrid1.$30i(event,0,0);']</value>
      <webElementGuid>74af9dc1-370e-4a9c-8b82-744316788a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_16Ptable']/tbody/tr/td/div/a</value>
      <webElementGuid>1c2ea8f3-608e-404c-883e-82656b29d347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1')]</value>
      <webElementGuid>376c66b3-1dc0-41d7-bfc7-ddf1defa8a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRANCH TFR CNS PAINT 511'])[2]/preceding::a[1]</value>
      <webElementGuid>84e8e27f-e1e9-48ad-96ec-cb8d42dede72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRANCH TFR CNS PAINT 511'])[3]/preceding::a[2]</value>
      <webElementGuid>40b4759b-fadd-4f94-b66f-e2e0e2bd1e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void')]</value>
      <webElementGuid>1e7d3fc2-80ec-44fe-ae6b-451fa3c9d3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/div/a</value>
      <webElementGuid>7024c192-9726-4ce4-80cd-0999a3023018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void' and (text() = '1' or . = '1')]</value>
      <webElementGuid>64c758b7-1a28-4eff-8ee3-d3f89107b84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
