<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DEMONSTRATION COMPANY 01Branch 510,Devi_e3962f</name>
   <tag></tag>
   <elementGuidId>5992a586-46dd-4262-8dde-43c480e2307f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_6</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59c98203-1499-4f74-84b7-5fd6ba8706c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_6</value>
      <webElementGuid>046eeffa-10a7-469f-99c0-de0a1aac3ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>isc_SplashPane_0</value>
      <webElementGuid>f7199035-4a97-4287-809d-58c07f6bafef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        DEMONSTRATION COMPANY 01Branch: 510, Device: roam510 Kino Rafael Manalo (manaki)</value>
      <webElementGuid>3151b8be-2ec9-41e2-a79e-a9ffdc1de215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_6&quot;)</value>
      <webElementGuid>70e78535-95c6-41d9-b28f-a575ba97f1dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_6']</value>
      <webElementGuid>65c37e32-18ad-47f3-a6ea-549ff5859d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_5']/div</value>
      <webElementGuid>66729d4c-6f1a-470d-a5aa-bad58659686e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>31640ff5-c3c2-4187-a826-2c0bd44fcddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_6' and (text() = '        DEMONSTRATION COMPANY 01Branch: 510, Device: roam510 Kino Rafael Manalo (manaki)' or . = '        DEMONSTRATION COMPANY 01Branch: 510, Device: roam510 Kino Rafael Manalo (manaki)')]</value>
      <webElementGuid>44b05c7e-6ec6-468c-bcb5-f504ab4776b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
