<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Supplier No.BRANCH TFR CNS PAINT 511Con_37407a</name>
   <tag></tag>
   <elementGuidId>0901ae2a-8b10-4f6b-b09b-ea168abed0d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_EA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_EA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_EA</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcab0fea-87f9-4f1e-8a3e-20979cd5999c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_EA</value>
      <webElementGuid>b946bb8c-035f-461c-b4dd-40efa9ff359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>isc_VLayout_25</value>
      <webElementGuid>efe18ec0-a393-4880-a086-c8c0c2494c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>4ae7c269-c538-49cc-88c9-0ad64dcaa396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return isc_VLayout_25.$lh()</value>
      <webElementGuid>2f03d908-f054-438d-a5dc-3b7c314ce446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>eb7dcf4c-33b6-403e-a6d4-f101d4ca6576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>03c3c84c-b87a-488e-b33e-d1d65b9644bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Supplier No.*BRANCH TFR CNS PAINT 511ContractPromotionRef.Order Branch510 - DEMONSTRATION BRANCH 510TypePurchase OrderDate RequiredShipping BasisSUPP - Supplier Direct Delivery Order FromAddressSuburb/CityStatePost CodeCountryPhone NumberFax NumberEmail AddressSave AddressShip ToAddressSuburb/CityStatePost CodeCountryInstructionsComments</value>
      <webElementGuid>df69399e-06b6-4739-b40c-c0442aa70add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_EA&quot;)</value>
      <webElementGuid>2e2dee02-77a1-4837-a50a-d9650fbe629c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_EA']</value>
      <webElementGuid>5a3007fc-b0e0-40c8-bb1f-bd3ff37097e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_E9']/div</value>
      <webElementGuid>f8088bc8-ab5f-4953-9b86-aca18b80ed6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::div[2]</value>
      <webElementGuid>bb6249a0-f4b7-46fe-923d-f875a1f76bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div</value>
      <webElementGuid>f5ce3a0f-7547-48d6-a238-68886ebec959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_EA' and (text() = '  Supplier No.*BRANCH TFR CNS PAINT 511ContractPromotionRef.Order Branch510 - DEMONSTRATION BRANCH 510TypePurchase OrderDate RequiredShipping BasisSUPP - Supplier Direct Delivery Order FromAddressSuburb/CityStatePost CodeCountryPhone NumberFax NumberEmail AddressSave AddressShip ToAddressSuburb/CityStatePost CodeCountryInstructionsComments' or . = '  Supplier No.*BRANCH TFR CNS PAINT 511ContractPromotionRef.Order Branch510 - DEMONSTRATION BRANCH 510TypePurchase OrderDate RequiredShipping BasisSUPP - Supplier Direct Delivery Order FromAddressSuburb/CityStatePost CodeCountryPhone NumberFax NumberEmail AddressSave AddressShip ToAddressSuburb/CityStatePost CodeCountryInstructionsComments')]</value>
      <webElementGuid>37a91812-7390-4047-99ab-7e47d2979786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
