<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BRANCH TFR CNS PAINT 511 (CHC511)</name>
   <tag></tag>
   <elementGuidId>849f9634-371f-4bf9-ad16-9630dce1a8e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_11Ptable']/tbody/tr/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelected > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BRANCH TFR CNS PAINT 511 (CHC511)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6182a7d-d8f0-43b9-ac27-c0ba56f4f1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>577fb267-b675-4301-84b5-3201eb2a5440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65c1acf9-4e78-41e8-993a-eb1fc6f2e552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BRANCH TFR CNS PAINT 511 (CHC511)</value>
      <webElementGuid>efa6bb6a-8901-434c-ad62-194041ed7d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_11Ptable&quot;)/tbody[1]/tr[1]/td[@class=&quot;pickListCellSelected&quot;]/div[1]</value>
      <webElementGuid>5b1a7fd1-f2f7-4723-97e8-449a67715f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_11Ptable']/tbody/tr/td/div</value>
      <webElementGuid>b6fbe04f-f3c4-4263-b166-3e255879d92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select suppliers with a word in the name beginning ...'])[1]/following::div[6]</value>
      <webElementGuid>cfc14e0b-30c9-49d0-adec-8c309de28504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Purchase Order'])[2]/following::div[11]</value>
      <webElementGuid>3644f20e-be2c-4ac0-acd9-8bbbf19bea7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BRANCH TFR CNS PAINT 511 (CHC511)']/parent::*</value>
      <webElementGuid>c9b94ff8-4fb3-45ce-91d7-438993daec75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>4ca84e1c-8a3c-4450-b1cd-30543d036db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BRANCH TFR CNS PAINT 511 (CHC511)' or . = 'BRANCH TFR CNS PAINT 511 (CHC511)')]</value>
      <webElementGuid>63d8e6c4-2512-439d-aa8a-39a3fad93ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
