<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Despatch Method_isc_19B</name>
   <tag></tag>
   <elementGuidId>b45d2b69-9973-4ffe-9733-d028d671bc02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_19B</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[4]/td[2]/table/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Despatch Method&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07551262-c2bf-478b-8699-4ac1c0f365ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_19B</value>
      <webElementGuid>145d80c2-db91-4904-a532-9183333f83bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_14</value>
      <webElementGuid>c0ef36c1-f4bb-4a82-92dd-230f0930de88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>f18ab2a3-d69f-4d6a-9296-83b74a7ade7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>11adc931-2a11-4b31-853a-4c7840064dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24924</value>
      <webElementGuid>5ea4d206-11c2-4d59-a25a-aca75ef11b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b7a399ed-5925-4359-ad41-bea663de6b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_19B&quot;)</value>
      <webElementGuid>6327c11c-1af3-4d24-87c1-9fc0ff7c9376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_19B']</value>
      <webElementGuid>c0caf5f9-efc2-42b5-951b-c1ea814d30b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_19C']/tbody/tr/td/div</value>
      <webElementGuid>bd4425bc-b6e3-4c7c-9f3c-acd7423dcf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/div</value>
      <webElementGuid>1cd1ae56-92d4-4d68-94a8-48f9c3557d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_19B']</value>
      <webElementGuid>0f99b252-e93f-4c2a-ab31-7da1a66687fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
