<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Purchase Orders_level3</name>
   <tag></tag>
   <elementGuidId>277a570e-3b65-48e8-bf5f-bf43e6423783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_TreeGrid_0_valueCell11' and (text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_TreeGrid_0_valueCell11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Purchase Orders&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9e3f0502-e617-4f8c-be0f-4d354e843d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_TreeGrid_0_valueCell11</value>
      <webElementGuid>3ddf0e4a-f508-427b-b279-6f5a382a9a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeTallCellSelected</value>
      <webElementGuid>cb764bae-4956-416c-a4d7-0e1907fbce1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>15529c9e-f02b-4615-bebb-1d16fd3cd39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_TreeGrid_0_valueCell11&quot;)</value>
      <webElementGuid>2cef619c-5e18-49dc-a8af-a37c0e65fa64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_TreeGrid_0_valueCell11']</value>
      <webElementGuid>14095923-7f7b-4257-8c86-2c176caae40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Etable']/tbody/tr[12]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>4efdc101-c919-47d5-8273-e97d9cf1b20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Processing'])[2]/following::td[4]</value>
      <webElementGuid>0a3f9f02-f300-41b0-8504-dc18d8ba8d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchasing &amp; Receipting'])[1]/following::td[8]</value>
      <webElementGuid>40889858-1326-44d5-ab9a-14ab21e36072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Receipting'])[1]/preceding::td[3]</value>
      <webElementGuid>910be568-da2b-4bee-ad87-b9562803c166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timber Packs'])[1]/preceding::td[7]</value>
      <webElementGuid>5f439ba3-f23d-45c4-84a0-4f454151c0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchase Orders']/parent::*</value>
      <webElementGuid>b43591d6-7c87-4e0e-9124-ac93c23595ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>09f16c8f-b51b-47f1-b5c0-09589a217315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_TreeGrid_0_valueCell11' and (text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      <webElementGuid>3b34ea97-1c06-47e2-8341-0f5208c345b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
