<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>purchaseOrderNo</name>
   <tag></tag>
   <elementGuidId>81d1eafe-2bd8-41f6-98c1-59287413d33e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.tabButtonTopSelectedFocusedOver > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_T0']/table/tbody/tr/td/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PO 51264100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>faffba8c-4ecf-4d9e-b48b-89a8459afa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PO</value>
      <webElementGuid>7be075dc-50ab-466d-87fc-b1b8e438804a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_T0&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;tabButtonTopSelectedFocusedOver&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;tabButtonTopSelectedFocusedOver&quot;]/span[1]</value>
      <webElementGuid>9c811067-86c6-4f32-9ad7-3032c1899a6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_T0']/table/tbody/tr/td/table/tbody/tr/td/span</value>
      <webElementGuid>24fa1f54-c53f-4856-8508-641713c4a5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Orders'])[1]/following::span[1]</value>
      <webElementGuid>7532a5eb-bfd9-4366-a2ee-afabe5f10581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[2]</value>
      <webElementGuid>158d959e-a9c9-4639-a1f8-8d4c860c0636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::span[1]</value>
      <webElementGuid>71b0775f-2a95-46cb-99e4-9e93d281e534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PO 51264100']/parent::*</value>
      <webElementGuid>48d6f986-b0b0-4b50-9081-b9f9fa6b4696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/table/tbody/tr/td/table/tbody/tr/td/span</value>
      <webElementGuid>886632ef-b0bd-4ba4-92f7-4d434ecf0b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PO 51264100' or . = 'PO 51264100')]</value>
      <webElementGuid>9ec19c78-c62b-43b4-a926-a868302dffef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
