<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Supplier No.BRANCH TFR CNS PAINT 511C_297ece</name>
   <tag></tag>
   <elementGuidId>58d62f36-85d5-4fe5-844d-26d98bc6c73c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_OJ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_OJ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_OJ</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>8e4fd5c2-b340-4a3e-b7c7-68a9dac01a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b6baa9ad-c9b5-4989-9b7c-03d8316d66ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_OJ</value>
      <webElementGuid>635bf241-873b-4710-b005-7c67856e7fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellspacing</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>077038fe-fa62-4d21-bb72-db27eff15576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellpadding</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9f6206d3-4e34-4734-b88a-ec5e533985b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5de2dbb7-ab77-4522-9267-c6456a9235c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supplier No.*BRANCH TFR CNS PAINT 511ContractPromotionRef.Order Branch510 - DEMONSTRATION BRANCH 510TypePurchase OrderDate RequiredShipping BasisSUPP - Supplier Direct Delivery</value>
      <webElementGuid>b5020dd3-a12a-4768-bf2e-ef6355948500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_OJ&quot;)</value>
      <webElementGuid>5dff4409-733c-471f-a64c-a76d4a91e176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='isc_OJ']</value>
      <webElementGuid>bd78ea5b-4f17-4bbf-b41f-8decb0aeb6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='isc_OI']/table</value>
      <webElementGuid>0ac2c49f-854c-44e8-97ca-735879bb0f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::table[1]</value>
      <webElementGuid>3694b99b-1e07-49af-88b4-e25fadb1d1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/form/table</value>
      <webElementGuid>7e574747-803b-41e1-ac9e-3cc5cd838b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id = 'isc_OJ' and (text() = 'Supplier No.*BRANCH TFR CNS PAINT 511ContractPromotionRef.Order Branch510 - DEMONSTRATION BRANCH 510TypePurchase OrderDate RequiredShipping BasisSUPP - Supplier Direct Delivery' or . = 'Supplier No.*BRANCH TFR CNS PAINT 511ContractPromotionRef.Order Branch510 - DEMONSTRATION BRANCH 510TypePurchase OrderDate RequiredShipping BasisSUPP - Supplier Direct Delivery')]</value>
      <webElementGuid>51bcaf15-6f98-46d6-bd03-22788413c50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
