<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CHC_PointofSale</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>75a4d059-207e-4415-a347-615fefff226e</testSuiteGuid>
   <testCaseLink>
      <guid>c741e877-8bb0-4b01-949f-13bcad90265c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/POS/Cash_Sale/POS_CashSale_CHC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>571aac75-fcfe-418f-812e-10aa55e023c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3549c197-1271-4fdf-8a40-a121c9faac5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CHC_Instance/POS/Account_Sale/POS_AccountSale_CHC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056ec2ff-650b-4baf-9d00-2c745cce20fa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
