<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DBC_SalesOrders</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ae1b0265-5a54-4e70-b339-28c951195cad</testSuiteGuid>
   <testCaseLink>
      <guid>66fb56e4-bd5e-4328-95ac-2025039bdafe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DBC_Instance/Sales_Orders/Account_Sale/SO_Account_Sale</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fa84b68-0261-438a-bf7f-b9097d8947c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8798e95-f296-4b09-8c93-a3e6bd972cf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DBC_Instance/Sales_Orders/Account_Sale/SO_AS_Validate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83635262-cb07-4264-b4eb-c9f020cb4de8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
