<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pick  Release</name>
   <tag></tag>
   <elementGuidId>3878b33a-eb64-448f-8e31-624a13f8206c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_VFtable']/tbody/tr[9]/td/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Pick &amp; Release' or . = 'Pick &amp; Release')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(9) > td.menuTitleField > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pick &amp; Release&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b75fe979-b57e-4292-8333-e88783852e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1f1ce7f8-88cb-4832-9d6f-a5ae3ff9bb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b47a120c-aad3-49fd-bbc4-bd977d7727b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick &amp; Release</value>
      <webElementGuid>4246deb4-348c-437d-b98a-51b00a354f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_VFtable&quot;)/tbody[1]/tr[9]/td[@class=&quot;menuTitleField&quot;]/div[1]</value>
      <webElementGuid>06aa69d7-d77c-487b-be1d-d911fc0690b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_VFtable']/tbody/tr[9]/td/div</value>
      <webElementGuid>6d81ad9b-9a96-46e5-9114-c72767561999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Buy-In'])[1]/following::div[3]</value>
      <webElementGuid>045cc4dd-f596-4465-b6e6-bd0a78d874db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold Prices'])[1]/following::div[6]</value>
      <webElementGuid>7c221909-9f25-40c2-a7bc-4a547e7a1348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Contract'])[1]/preceding::div[3]</value>
      <webElementGuid>b20f0b37-eaa6-4e9a-b0ea-24e20ea0b7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linked PO'])[1]/preceding::div[6]</value>
      <webElementGuid>bc735516-65fb-44b8-ae5f-b20fce31e041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pick &amp; Release']/parent::*</value>
      <webElementGuid>4b866af3-90a0-4e98-bf94-2527b2bb8887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/table/tbody/tr[9]/td/div</value>
      <webElementGuid>2acfedce-32f5-40fc-aea5-8bc28bf53379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pick &amp; Release' or . = 'Pick &amp; Release')]</value>
      <webElementGuid>68c248cc-5d50-4b25-b59b-c3fc6a0ff7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_2A5table']/tbody/tr[9]/td/div</value>
      <webElementGuid>4279f2e9-3be3-4041-bd3c-6f30769bddaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/table/tbody/tr[9]/td/div</value>
      <webElementGuid>2c1ae0f8-0985-4887-a6a5-abba5f587287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
