<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_223 Bob</name>
   <tag></tag>
   <elementGuidId>3ead0d45-0169-417c-b6ed-a3a9158485c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelected > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_1KNtable']/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_1KNtable >> internal:text=&quot;223 Bob&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a85f350-ae95-459f-931e-e4c324706fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>106e12dc-4394-4727-bd11-b20fe21fa7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cfaf8c04-b2e7-4352-904c-55deee690835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>223 Bob</value>
      <webElementGuid>9145e21d-af3f-49b3-abdc-fb2d5b5f61a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1KNtable&quot;)/tbody[1]/tr[1]/td[@class=&quot;pickListCellSelected&quot;]/div[1]</value>
      <webElementGuid>1f6556ef-b765-4ce4-8886-2ae1a680fef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1KNtable']/tbody/tr/td/div</value>
      <webElementGuid>98fb09e7-16df-43fd-8f1a-a87ed817e38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PickingGroup'])[2]/following::div[6]</value>
      <webElementGuid>09ac3601-c749-4b8e-90cf-528a384385ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[13]</value>
      <webElementGuid>77960f2b-0800-4d7e-a177-03c010ceb161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>59fd7650-1aef-469e-81a6-09a539947db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '223 Bob' or . = '223 Bob')]</value>
      <webElementGuid>38bf9092-665b-48cd-ade9-955eb168db03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
