<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalesOrderLink</name>
   <tag></tag>
   <elementGuidId>4b20ab9f-309d-4c17-9607-0483c761b9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='if(window.salesOrderView_ttResults_ListGrid1) return salesOrderView_ttResults_ListGrid1.$30i(event,0,0);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;26498751&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67b9c37c-d765-4f09-8949-178665010c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>9c0a73d9-23aa-4f2e-b0dd-7d6b4790e9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>1ca32ce8-d763-4384-a48c-c0267a3e675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.salesOrderView_ttResults_ListGrid1) return salesOrderView_ttResults_ListGrid1.$30i(event,0,0);</value>
      <webElementGuid>ea82f196-c098-4d9f-9814-daa5b16da6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26498751</value>
      <webElementGuid>75bceb83-52dc-4262-ab0c-2803d37796a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_C6table&quot;)/tbody[1]/tr[1]/td[@class=&quot;cellSelectedOver&quot;]/div[1]/a[1]</value>
      <webElementGuid>86a2b290-793e-4a4f-ba10-69b2c8604fd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(window.salesOrderView_ttResults_ListGrid1) return salesOrderView_ttResults_ListGrid1.$30i(event,0,0);']</value>
      <webElementGuid>cc509f79-1e31-4ed7-b2a4-c0e963dac923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_C6table']/tbody/tr/td/div/a</value>
      <webElementGuid>31e671b4-a320-44fc-8796-6ff0705a009b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'26498751')]</value>
      <webElementGuid>e1a06d6c-bf0e-4378-a8c7-e321bc5b6a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section'])[1]/following::a[1]</value>
      <webElementGuid>87508518-e056-448a-bb58-170393dee075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CustomerPhase'])[1]/following::a[1]</value>
      <webElementGuid>0cac9760-2861-4530-835f-9d1d6dfce338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAHLSENS-T/FER A/C-MYRTLEFORD'])[1]/preceding::a[1]</value>
      <webElementGuid>b925c5dd-44b8-4dc4-b9f0-62a3230e8506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[2]/preceding::a[1]</value>
      <webElementGuid>4c0a4795-68ae-410e-bf64-2d10ce71dbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26498751']/parent::*</value>
      <webElementGuid>576552bc-4663-43ee-b42e-c6acdb28b92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void')]</value>
      <webElementGuid>374d214a-e2a4-446f-96f8-a6a93381334c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7546a4bf-6048-4098-8780-0061f0ec9829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void' and (text() = '26498751' or . = '26498751')]</value>
      <webElementGuid>723de8e0-1e49-4912-8a1c-ecd60f783c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
