<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SO_Value_Tab</name>
   <tag></tag>
   <elementGuidId>5534eb8a-b6bb-4640-b73c-f35f694085cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.tabButtonTopSelectedOver > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div/table/tbody/tr/td/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SO 26498751/0&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>878c0137-2de6-4450-b711-9e7928c8d2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SO 26498751/0</value>
      <webElementGuid>537a8f8a-6974-4c01-841d-60a0aca49412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_195&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;tabButtonTopSelectedOver&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;tabButtonTopSelectedOver&quot;]/span[1]</value>
      <webElementGuid>b342f7ee-6edd-4a2f-908a-29350c4a8d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_195']/table/tbody/tr/td/table/tbody/tr/td/span</value>
      <webElementGuid>a11a7cc2-8eb2-4dbe-954f-c883928b896c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Orders'])[1]/following::span[1]</value>
      <webElementGuid>8520caa5-575e-4718-90c4-951d9ac33ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[2]</value>
      <webElementGuid>9dd1c08e-363b-4015-b31f-b54ac3b06024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::span[1]</value>
      <webElementGuid>1ffe2a7a-5813-49dc-897a-7e5c22ffb808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dahlsens Frameworks'])[1]/preceding::span[1]</value>
      <webElementGuid>0eb69928-d449-4fba-a2ec-c1e68a580111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SO 26498751/0']/parent::*</value>
      <webElementGuid>a9159c1f-f0a8-4bd7-84a9-69e6f6729013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/table/tbody/tr/td/table/tbody/tr/td/span</value>
      <webElementGuid>13437c82-9979-4b2f-aec4-e8c3e728c4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SO 26498751/0' or . = 'SO 26498751/0')]</value>
      <webElementGuid>a43241d0-afdd-4960-b1f2-52bafd93eb53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
