<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_OK</name>
   <tag></tag>
   <elementGuidId>65045e58-0220-4c58-9bcb-44d246642426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.buttonRoundedOver</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'OK' or . = 'OK')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_1AC']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;OK&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8e53c719-fd84-4ea2-a235-636f448a4346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1ba8ee0-3f98-4903-a765-a442caa70b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonRoundedOver</value>
      <webElementGuid>391142e0-3347-41b1-82bb-dd008a5756e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>41e5c7f2-a64c-4cc6-a814-4ff1a166d684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>aabf91dc-d8ac-4635-9cd6-2002957c29ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>isc_IButton_3.$47()</value>
      <webElementGuid>5293ed83-ee42-4b1c-9e27-902b6394a05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>c76823a8-c4fd-4e5d-8cc2-1c832012109d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1AC&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;buttonRoundedOver&quot;]</value>
      <webElementGuid>10cdcea5-3888-4449-8f16-f6fceb522ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1AC']/table/tbody/tr/td</value>
      <webElementGuid>ad8b3cc5-bc8b-409d-81c3-922525a572b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There were errors during the save'])[1]/following::td[2]</value>
      <webElementGuid>eae19912-a945-4cc7-a01b-2642f02660da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Order'])[1]/following::td[6]</value>
      <webElementGuid>41db6237-44f8-460d-9715-62b93c2fca6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Order Maintenance'])[1]/preceding::td[1]</value>
      <webElementGuid>b44f4b17-82e2-45ae-82a0-58fdb0b5dc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='K']/parent::*</value>
      <webElementGuid>ec50e9ae-19e8-42b7-a213-64f4d27a5fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div[2]/div/div/div/table/tbody/tr/td</value>
      <webElementGuid>fb3e1fe0-eea0-4994-8547-6b6a3894d0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>5ef33bf9-b9e4-4556-8298-b87e09ec3ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
