<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Print Delivery Docket_isc_1XB</name>
   <tag></tag>
   <elementGuidId>48482ad6-1843-4a9a-9667-1e0b32b21a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_1XB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_1XB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_1XB</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>af5b667f-3125-4d3d-95f1-92702c21c807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>f6cbc374-9cbe-4f10-9ae3-8ce653de2676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formCell</value>
      <webElementGuid>f18b1b27-2c6c-4202-b3d5-bb374ac26fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c1d3c1c6-ac70-48c4-b918-5b743aaa4583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_1XB</value>
      <webElementGuid>98280ca1-c027-4156-b99c-c6bb77a3e2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_CheckboxItem_10</value>
      <webElementGuid>96b526f7-f55e-493c-bc54-f71304be46ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1XB&quot;)</value>
      <webElementGuid>27fdfa54-656f-4ce3-a731-10573d676d32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_1XB']</value>
      <webElementGuid>77da0f26-08d7-4bf1-8304-aa36ec3bc3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1VH']/tbody/tr[15]/td[2]</value>
      <webElementGuid>d34c2255-c872-47b4-a94b-f665e3bcec8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Delivery Docket'])[1]/following::td[1]</value>
      <webElementGuid>bd3ca988-df73-4f05-afbd-1527a285c14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::td[8]</value>
      <webElementGuid>51266bab-a5b9-40e7-9bf9-60f93f2c8b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Delivery Docket'])[1]/preceding::td[2]</value>
      <webElementGuid>4330dd47-ac32-410f-8921-851d96738d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Printer Address'])[1]/preceding::td[5]</value>
      <webElementGuid>7f25e364-ff0e-48e6-809a-4df4f8a6df83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]</value>
      <webElementGuid>37944c9d-eaf7-4687-aada-20864e312653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_1XB']</value>
      <webElementGuid>37af0109-dada-4eb6-8e52-5147ace39952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
