<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Receipt Goods</name>
   <tag></tag>
   <elementGuidId>9f4c5772-baa7-4423-a468-60b4df299a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_KJ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_KJ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_KK</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0c2961e-0a63-49cb-9a60-a7ad67edbf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_KJ</value>
      <webElementGuid>0a64895d-2507-4045-a454-946ee9c8eee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a1b81f38-d32e-4414-9860-a0c62a75d49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Receipt Goods</value>
      <webElementGuid>c4e0a19a-9e92-44a4-9694-80fc4fb5aba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_KJ&quot;)</value>
      <webElementGuid>1b377c51-6dea-49b5-9921-fb9417dc6794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_KJ']</value>
      <webElementGuid>bb9f727d-04ae-4a10-961a-336389293cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_KK']/table/tbody/tr/td/div</value>
      <webElementGuid>fe224eb8-8e45-4113-8185-e9aaa19737bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt Date'])[1]/following::div[3]</value>
      <webElementGuid>5ee66e2f-585b-4669-864c-976ab58f52b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docket Number'])[1]/following::div[3]</value>
      <webElementGuid>2993eb0c-1f79-4bed-b188-c98b7a62fc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rapid Entry'])[1]/preceding::div[1]</value>
      <webElementGuid>017aa599-b847-4e26-9d26-62d9f4b2087a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept Backorders'])[1]/preceding::div[6]</value>
      <webElementGuid>bb48e203-23ef-4bb3-8297-8910dd4584f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Receipt Goods']/parent::*</value>
      <webElementGuid>e948e9b7-476d-421e-bdfc-58b00789ede8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>b8ffaefc-8298-45e5-8c5a-1cf05ea8887a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_KJ' and (text() = 'Receipt Goods' or . = 'Receipt Goods')]</value>
      <webElementGuid>1c1cd550-0dad-451f-97a0-af4ecc5ac129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
