<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Stock Receipting</name>
   <tag></tag>
   <elementGuidId>aba54a83-f230-4b7b-ae44-581f9cbb3473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_MenuPopout_2_0_valueCell17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[18]/td/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Stock Receipting&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f7ad4047-f897-4e1b-8d2a-b0e62afefb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_MenuPopout_2_0_valueCell17</value>
      <webElementGuid>c3cbd4e7-bca1-4ed4-94b1-549246cf2bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeCellSelectedOver</value>
      <webElementGuid>af24008f-dd59-498e-bf3e-7cb78b03a144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Receipting</value>
      <webElementGuid>e8ebf150-6a6b-4cfb-900d-e9f074a42c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MenuPopout_2_0_valueCell17&quot;)</value>
      <webElementGuid>76d18faf-02b8-4066-87a3-1f1a09792747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_MenuPopout_2_0_valueCell17']</value>
      <webElementGuid>79b67bd3-1c51-4e21-9c5e-778747144dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Ctable']/tbody/tr[18]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>fba6debb-8f32-4d6e-8a50-69fe14cb37ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Orders'])[1]/following::td[4]</value>
      <webElementGuid>247e694d-1e07-4a2a-b64d-45b25af27735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Requisitions'])[1]/following::td[8]</value>
      <webElementGuid>8a9fb0ca-eefa-4d94-b564-f0ac20a0f3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Transfers'])[1]/preceding::td[3]</value>
      <webElementGuid>ab64f474-1066-40d6-b875-54367deed686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Pricing'])[1]/preceding::td[7]</value>
      <webElementGuid>11b05a28-6c46-45fe-9170-1c2e1a346c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stock Receipting']/parent::*</value>
      <webElementGuid>ed007d39-013b-4d2f-92cf-7c77bd888529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>bd290280-0c3f-46ed-8b59-9f3170e6b7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_MenuPopout_2_0_valueCell17' and (text() = 'Stock Receipting' or . = 'Stock Receipting')]</value>
      <webElementGuid>90cfddc6-a86f-4bb9-a620-f612748c1939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
