<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Stock Movements</name>
   <tag></tag>
   <elementGuidId>1dcd0031-49b2-4fcb-820d-0da418473cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.buttonNeutralActionFocusedOver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/div/div/div[2]/div/div/div/table/tbody/tr/td[(text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Stock Movements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e6ed33c1-d90e-4937-99dc-00b571cfb40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07327cb3-2afc-4e0e-a3b2-491851702a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonNeutralActionFocusedOver</value>
      <webElementGuid>958eaae8-f723-40a0-b6f8-54e9326a0fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>16338403-c699-46ad-8163-8fa995afe427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>7c204d67-201f-4107-a5c5-7322de5500c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>isc_ButtonItem_23_button.$47()</value>
      <webElementGuid>106ab8b0-9251-42fe-8e3d-e8e2c770c0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Movements</value>
      <webElementGuid>083c6ed8-22d9-47b9-8fbc-098a7f4dc3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1JQ&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;buttonNeutralActionFocusedOver&quot;]</value>
      <webElementGuid>af820ef1-f4d4-476b-a698-1d0feb026d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_1JQ']/table/tbody/tr/td</value>
      <webElementGuid>1214d685-0f9c-4a8c-839a-8c283804f572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Price'])[1]/following::td[13]</value>
      <webElementGuid>fcd4cdfd-794f-4cd1-9dce-9980d6d41f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Status'])[1]/following::td[15]</value>
      <webElementGuid>77670bcd-9810-44d9-9024-6d3f505764b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Enquiry'])[2]/preceding::td[1]</value>
      <webElementGuid>10286d4b-bc09-4776-8c02-9fd10c029419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Enquiry'])[1]/preceding::td[2]</value>
      <webElementGuid>40e4cba2-2452-4bb8-8903-7390187f4e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/table/tbody/tr/td</value>
      <webElementGuid>1aea7dde-7fb1-4fbb-a842-034cffd96e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      <webElementGuid>d103e8eb-09bc-41c7-9e4d-fad01c9fa2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
