<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stock Movements</name>
   <tag></tag>
   <elementGuidId>deb67ba1-b606-4d29-b0fd-5efc240b4007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/div/div/div[2]/div/div/table/tbody/tr/td/div[(text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_103</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6f80401-ec9a-486a-b1e5-d75d54779b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_102</value>
      <webElementGuid>3833c5fe-c7ab-4048-968e-bba3ea5f811a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0b688aad-1197-4be7-bbb2-042536701095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stock Movements</value>
      <webElementGuid>d7d30865-c2df-499a-b050-e45afa9606b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_102&quot;)</value>
      <webElementGuid>cd9fb41b-5ec2-457f-93ff-6ef47614c328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_102']</value>
      <webElementGuid>31c3bbbc-e378-4da1-a91e-34b6c04ea5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_103']/table/tbody/tr/td/div</value>
      <webElementGuid>cd7df420-3d72-4c02-acb4-8c6e3d458b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Price'])[1]/following::div[11]</value>
      <webElementGuid>ecb5521b-2dce-4a15-8f71-34fc40977bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Status'])[1]/following::div[13]</value>
      <webElementGuid>61e65b31-ecee-4316-b70b-7ac709e83bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Enquiry'])[2]/preceding::div[1]</value>
      <webElementGuid>428e42f0-3ad1-4338-b16a-e170f1135c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Enquiry'])[2]/preceding::div[3]</value>
      <webElementGuid>b8cfe2cd-fb4e-4e7e-8a53-e43c747aa655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>4350e8eb-63fc-4b51-974f-69857e01b02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_102' and (text() = 'Stock Movements' or . = 'Stock Movements')]</value>
      <webElementGuid>63fd306c-990f-4710-81fd-ae957db9008e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
