<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DBC_PointofSale</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2c3a46c0-bb6a-41a6-aea0-cdda1bcbbec1</testSuiteGuid>
   <testCaseLink>
      <guid>699f1b53-809b-47e1-91a2-33d459a114e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DBC_Instance/POS/Cash_Sale/POS_CashSale</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f53255fb-dc7e-4742-8b92-4a38ba4fdba5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>633626ca-5832-4ecf-9d26-285eba812240</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DBC_Instance/POS/Account_Sale/POS_AccountSale</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad42caef-b44c-4b51-be4d-13ed33f1c024</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd00345-96e2-403f-bdcd-b1e4f8133622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d6ef38-4358-4915-9aaa-8def8669cc09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad664eaf-3e78-46a6-9d8a-2da4cada7825</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
