<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Desp. Method_isc_KM</name>
   <tag></tag>
   <elementGuidId>3a15d6a7-a486-42d0-902c-c768fe82e8d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_KM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[11]/td[2]/table/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_KM</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d80b31c-8a64-4871-a492-adf2b774a464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_KM</value>
      <webElementGuid>d0757deb-89db-4611-bcaa-048ad122e44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_10</value>
      <webElementGuid>8e0e1321-dac9-4c4f-a620-bad9924214ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>dd4759ae-4aff-4080-9c4b-24cd8c612ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>8122c17a-5363-45fc-97d6-5e2ec9526c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9918</value>
      <webElementGuid>a8b744de-5407-46de-8ed2-48583e152979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>19c8759d-2af0-4c0e-b2d9-322af155f27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_KM&quot;)</value>
      <webElementGuid>b2d42c9c-5d4e-4bc6-8d48-fa3beaf32aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_KM']</value>
      <webElementGuid>bf244054-db62-4900-a69f-ef0b4b75e91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_KN']/tbody/tr/td/div</value>
      <webElementGuid>37df18b5-b76a-4700-93a5-69dd2e357434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/table/tbody/tr/td/div</value>
      <webElementGuid>f8e57d01-cea9-4c32-a261-54980eb13703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_KM']</value>
      <webElementGuid>57abf593-e651-4d8e-a47f-3c3745b33e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
