<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SuburbCity</name>
   <tag></tag>
   <elementGuidId>5bfe9fd5-862c-40da-a45b-e85928b3f628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_MO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_MO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Suburb/City&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77c79d16-a9cb-4d32-a9a2-a7ec88d56942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>1344fcad-9014-4f66-88b8-7eab8d551165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deliverToAddress3</value>
      <webElementGuid>9ea00a7e-ef96-44b7-999d-809e4604c6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_MO</value>
      <webElementGuid>9d60c6c7-3657-465e-b747-52786de7f8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e49f01a5-cc7a-4bdd-80eb-cf27ceb15f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_46</value>
      <webElementGuid>98f938db-d4e3-4a0b-b1ed-23cf7531298f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>3539a3e4-a43a-4807-bf1d-0ecf7b373dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>202f1bc6-a079-4abe-a08a-ae1034f3e849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_46._handleInput()</value>
      <webElementGuid>ba3888b2-8828-41db-8341-561c5b73406f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_46 == null) return;isc_TextItem_46.$1162()</value>
      <webElementGuid>1f1a970a-fce7-419b-840e-f0ff56aaff63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>09bc9e2f-0174-4905-bb0f-bb2dbc1848af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItemFocused</value>
      <webElementGuid>0e04bc68-c15d-4a19-a046-954b6c01d454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10224</value>
      <webElementGuid>74e3de8f-8689-4bb1-a79e-f51b2f9373a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MO&quot;)</value>
      <webElementGuid>64306988-77f8-4688-87f3-dd3aac6afc00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_MO']</value>
      <webElementGuid>daa6f04b-6eaa-4ae5-b8d6-29e576753c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_MQ']/input</value>
      <webElementGuid>478dac15-cf5e-4836-815d-64d6050038bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>bea517b4-ef2d-4561-a0c7-6efe29b107ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'deliverToAddress3' and @id = 'isc_MO']</value>
      <webElementGuid>2ce50462-02f8-40b6-9454-665320145717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
