<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer_idCustX</name>
   <tag></tag>
   <elementGuidId>e0eb6cff-56c9-4656-9bf7-07282ec328b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_IT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_IT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New Sales Order&quot;i >> internal:label=&quot;Customer&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d7fa61d-6df1-45e6-bfc8-9b1356b52e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>37caf5b1-7dad-4037-bbec-3f94ec7eb136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idCustX</value>
      <webElementGuid>03bea93e-ca21-47fd-ac7b-1b585d081932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_IT</value>
      <webElementGuid>325f32b3-968e-4995-a19e-1b33c2d0143a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee551a2d-d8c8-43da-8ef9-7b52a0f0f815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_3</value>
      <webElementGuid>50d60cc8-56e1-461f-a861-64a71c189f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>3af3e25e-d50e-44de-967d-22b1004a7b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1324f0a-0542-4e2c-bbe9-7aa236d04b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_3._handleInput()</value>
      <webElementGuid>df1414ff-79b9-49a3-9b67-d19be4752d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_ComboBoxItem_3 == null) return;isc_ComboBoxItem_3.$1162()</value>
      <webElementGuid>e387a32d-3154-4b45-9d44-e2f3a97cbcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>1c3afcd4-7078-4223-98a6-814949ffa380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSuggestBoxFocused</value>
      <webElementGuid>caec465a-9d59-4ea0-a302-6702093a0516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9895</value>
      <webElementGuid>19d3f43c-f375-4024-bdc2-9d5c6c9171b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_IT&quot;)</value>
      <webElementGuid>71d7ec9e-143d-4ba2-89db-3c36bee3542d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_IT']</value>
      <webElementGuid>925db202-c5b3-4927-9a33-5112d2e00113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_QN']/tbody/tr/td/input</value>
      <webElementGuid>2c2c7c97-f67c-4b22-9917-13fa96da57f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>ff64f448-cfda-484a-b236-8b51692a25a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'idCustX' and @id = 'isc_IT']</value>
      <webElementGuid>75f63540-cd93-436c-a0fe-f34aee750fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
