<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Sales Orders</name>
   <tag></tag>
   <elementGuidId>ed679628-b5a1-4793-b050-20daf7de4db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_MenuPopout_2_0_valueCell4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='isc_MenuPopout_2_0_valueCell4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sales Orders&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>21c80394-12d9-4c00-b210-ad815f524025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_MenuPopout_2_0_valueCell4</value>
      <webElementGuid>e92b6ffb-602b-4d35-bd37-985d031f5f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeCellSelectedOver</value>
      <webElementGuid>4ae50fd4-cc82-4ef4-befb-eacf1aff75c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales Orders</value>
      <webElementGuid>22f6e86d-4f0f-4cc9-bbe3-1932684d03f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_MenuPopout_2_0_valueCell4&quot;)</value>
      <webElementGuid>4cbf6b8f-8927-4075-9985-e5e1d2369278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='isc_MenuPopout_2_0_valueCell4']</value>
      <webElementGuid>1ec15983-45f6-4b1e-a460-04fcf661c4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_7Ctable']/tbody/tr[5]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>67b8a194-fe90-4cdd-aba1-9100ff729907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/following::td[4]</value>
      <webElementGuid>436dda12-93d8-4b06-8f33-1e3ecbbaf41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Point Of Sale'])[1]/following::td[8]</value>
      <webElementGuid>1df240e4-399c-4b73-a8f6-9b868292f1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Notes'])[1]/preceding::td[3]</value>
      <webElementGuid>a77c3313-62f9-4e03-b8b3-28f278ac6cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picking Dashboard'])[1]/preceding::td[7]</value>
      <webElementGuid>2aedb84a-ae6d-4042-acfe-9b3a60287420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales Orders']/parent::*</value>
      <webElementGuid>fa44fa5a-cd4f-48d2-b9ca-396ea2c3fd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/table/tbody/tr/td[3]</value>
      <webElementGuid>704bf36e-d98e-4ffc-846c-cea4af53ab1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'isc_MenuPopout_2_0_valueCell4' and (text() = 'Sales Orders' or . = 'Sales Orders')]</value>
      <webElementGuid>3c716f9e-eb8a-43ff-bd86-aef8ff44e42f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
