<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tfer SO</name>
   <tag></tag>
   <elementGuidId>0060ae60-9f13-4474-98df-b2fc993ae3fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='isc_137']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_137</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tfer SO: 26498751&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e38f2866-d8fd-478b-9c3b-9259ec1d425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_137</value>
      <webElementGuid>eb5bc8b6-7b95-465a-b272-252e8e7c8082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void</value>
      <webElementGuid>49363bd5-dc61-4db9-84ef-64a691ca8523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>javascript</value>
      <webElementGuid>3b4b7a5a-a11b-46f8-81fd-0a02bd9c55a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9582</value>
      <webElementGuid>0d5c7563-4476-47c7-af88-e6c0e04d9458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.isc_LinkItem_6) return isc_LinkItem_6.$30i(event);</value>
      <webElementGuid>e76e31ff-f6ab-4cf8-9912-cb218fda13bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>d523e766-2a85-47db-919b-6ee825933980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tfer SO: </value>
      <webElementGuid>8be0e9b8-e115-4dfc-b15c-9d7f3a9359ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_137&quot;)</value>
      <webElementGuid>4c45b79a-372e-43c5-9806-16bc6e3a0b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='isc_137']</value>
      <webElementGuid>fe53c933-d4f9-493a-beb3-7bc1cd547fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_135']/a</value>
      <webElementGuid>1094db12-c4ad-437e-b3d7-1fb4a381f36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tfer SO: 26498751')]</value>
      <webElementGuid>562435d8-77ce-4f63-a342-7cf15eabc24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDFSrc'])[1]/following::a[1]</value>
      <webElementGuid>83d85308-46a0-442e-92fa-b2cb9618fc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volume(m3)'])[1]/following::a[1]</value>
      <webElementGuid>16a8c44c-1c63-42f8-aba4-0fc4dc5b4de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an item to open'])[1]/preceding::a[1]</value>
      <webElementGuid>902ef625-84d1-4970-bf92-4bfe00685149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/preceding::a[1]</value>
      <webElementGuid>135b1303-979c-4f31-a199-7e5ba67b378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tfer SO: 26498751']/parent::*</value>
      <webElementGuid>bbfce8d6-c2f1-4bb4-9ddd-41ad9f524a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void')])[9]</value>
      <webElementGuid>082b7b1a-b4a6-4151-bb16-bffbc1e2a2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a</value>
      <webElementGuid>b095e0c2-3451-46be-aaff-5bd06a21187e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'isc_137' and @href = 'javascript:void' and (text() = 'Tfer SO: 26498751' or . = 'Tfer SO: 26498751')]</value>
      <webElementGuid>33baa2d9-9cf7-4969-a4a3-901d68f103f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
