<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DAHLSENS TRANSFERS ALBURY (DBC223)</name>
   <tag></tag>
   <elementGuidId>44c306f3-f49d-4147-9c95-e5cf8cda8dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'DAHLSENS TRANSFERS ALBURY (DBC223)' or . = 'DAHLSENS TRANSFERS ALBURY (DBC223)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelected > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DAHLSENS TRANSFERS ALBURY (DBC223)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0f1fd82-955b-4cba-a5a0-ee8d7d7271d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>594e2e08-77dc-43ab-bcc9-8b49a70a799f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e1aca40-409f-4659-8ba8-48f0fbba231b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAHLSENS TRANSFERS ALBURY (DBC223)</value>
      <webElementGuid>bf3b7a5f-9cad-4a1a-a631-aba66e602671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_LTtable&quot;)/tbody[1]/tr[1]/td[@class=&quot;pickListCellSelected&quot;]/div[1]</value>
      <webElementGuid>666d3fc3-4b14-4920-b9c5-743c345707b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_LTtable']/tbody/tr/td/div</value>
      <webElementGuid>03ab8090-9b7c-47f4-9cb2-9d3fe9024a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Purchase Order'])[2]/following::div[10]</value>
      <webElementGuid>529ad271-9a3d-43a6-adfd-7699d65f529f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Purchase Order'])[1]/following::div[12]</value>
      <webElementGuid>927ac7df-77f2-40ba-9d49-1193501f3f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAHLSENS TRANSFERS ALBURY (DBC223)']/parent::*</value>
      <webElementGuid>138e2e4f-d02d-44f7-9eb9-a05aac21f799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/table/tbody/tr/td/div</value>
      <webElementGuid>e0aa4363-4948-4cb4-8ae8-9a8cfdd87055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DAHLSENS TRANSFERS ALBURY (DBC223)' or . = 'DAHLSENS TRANSFERS ALBURY (DBC223)')]</value>
      <webElementGuid>5a1665dd-ccf8-4b88-ada4-83bfcaf56d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
