<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DLV - Supplier Delivery</name>
   <tag></tag>
   <elementGuidId>2a76d0f4-5210-4f7b-b192-f5d8d9fa4447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_OQtable']/tbody/tr[2]/td/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'DLV - Supplier Delivery' or . = 'DLV - Supplier Delivery')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pickListCellSelectedDark > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_OQtable >> internal:text=&quot;DLV - Supplier Delivery&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07916b14-ea64-4bb2-a98f-fd3766c30a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c337082c-447f-498c-867a-281bec232531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35c882a2-2039-4acc-b4d2-d9f3925c40b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DLV - Supplier Delivery</value>
      <webElementGuid>7fc26583-036b-4722-8740-383070091e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_OQtable&quot;)/tbody[1]/tr[2]/td[@class=&quot;pickListCellSelectedDark&quot;]/div[1]</value>
      <webElementGuid>53cf7d86-2171-4e5d-af93-01440f834f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_OQtable']/tbody/tr[2]/td/div</value>
      <webElementGuid>a59d0996-834f-4cc1-b162-bb8834648201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deliv - Supplier Delivery'])[1]/following::div[1]</value>
      <webElementGuid>08037820-d89d-4f4e-a908-99214198e821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::div[8]</value>
      <webElementGuid>66e5307a-5156-44f8-b36f-7a3316a3b5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DPT - Deliver to Depot'])[1]/preceding::div[1]</value>
      <webElementGuid>a348f5f1-ac56-4433-8a7a-ba9049ede9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PickU - Pickup from Supplier'])[1]/preceding::div[2]</value>
      <webElementGuid>e3be1059-e9b2-4bb1-936e-9f7bbc2c65cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/table/tbody/tr[2]/td/div</value>
      <webElementGuid>ed4f4dfa-f2bd-4480-bb36-2905bfb8b0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DLV - Supplier Delivery' or . = 'DLV - Supplier Delivery')]</value>
      <webElementGuid>ec9fb7bc-66fb-42e4-b47e-e298a10013bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
