<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Order FromAddressSuburbCityStatePost Co_17de1f</name>
   <tag></tag>
   <elementGuidId>83d3cf03-0e94-4e3b-bc25-550f9dc3890a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_V7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_V7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_V7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eea900bc-e356-4d55-87b5-9a8f8628835f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_V7</value>
      <webElementGuid>e93c8aae-ce35-40ff-b800-5f41b8d6f651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eventproxy</name>
      <type>Main</type>
      <value>isc_Fluid_0_ttPorder_Form2</value>
      <webElementGuid>e5088b90-acd5-40dd-a484-84fc6def4f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activityform</value>
      <webElementGuid>a8e3bf0f-c982-4e67-a6f7-41f007238d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onscroll</name>
      <type>Main</type>
      <value>return isc_Fluid_0_ttPorder_Form2.$lh()</value>
      <webElementGuid>5b095f55-4c13-4029-a4f4-2b0bf4ead474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order From :Address :Suburb/City :State :Post Code :Phone Number :Fax Number :Email Address : Save Address</value>
      <webElementGuid>beee70ef-215f-4803-9acf-49e8531efde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_V7&quot;)</value>
      <webElementGuid>65cc3299-2c3e-40fa-bdc5-ecb68241e670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_V7']</value>
      <webElementGuid>bf4a58b1-3861-4e79-8cd7-9b48a6d41743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_V6']/div</value>
      <webElementGuid>a5109a14-5a13-401c-a1b2-b2ad67c5036b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Basis'])[1]/following::div[4]</value>
      <webElementGuid>e29763cf-064e-4a14-b103-00122489024a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Required'])[1]/following::div[5]</value>
      <webElementGuid>a3a7060e-6aa3-415e-b3cf-d89dc0b58208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>62aed2f6-b9e7-452c-be1e-982d7059836e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_V7' and (text() = 'Order From :Address :Suburb/City :State :Post Code :Phone Number :Fax Number :Email Address : Save Address' or . = 'Order From :Address :Suburb/City :State :Post Code :Phone Number :Fax Number :Email Address : Save Address')]</value>
      <webElementGuid>97738348-bb9b-4079-be35-0083788b4e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
