<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_P_idProd</name>
   <tag></tag>
   <elementGuidId>bcd03383-ae35-4fe6-acb6-b0bd4b82f5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div[3]/div/div/div/div/div/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'TEXT' and @name = 'idProd' and @id = 'isc_W4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_W4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Product&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>332595e3-ba3c-4ec4-9ecd-84f7206f8400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>87f63ae5-beba-4581-8e3f-e4b3141d177a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idProd</value>
      <webElementGuid>687c2833-1766-436c-bd1f-079f2b13dd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_W4</value>
      <webElementGuid>773cb616-9313-4e7b-9885-41ea5d6d5381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1df284fc-59ab-4699-853d-7fdd9516d3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_38</value>
      <webElementGuid>3eff40d3-92fd-46de-8bf4-6a36d5dffb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>868f6e87-97d0-494d-add1-d026d9ee0bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd3b073e-57ff-4aa9-9ead-bff7227d69ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_38._handleInput()</value>
      <webElementGuid>f0ace9c1-8a27-492e-b143-52a7bda82af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_38 == null) return;isc_TextItem_38.$1162()</value>
      <webElementGuid>64a1fa47-faf5-4070-89b3-d54abd8918e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>4ebdbf98-e74f-4850-8523-a332aaf6df17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItemFocused</value>
      <webElementGuid>34155f4c-8871-46b6-b706-80bc4e6cddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5566</value>
      <webElementGuid>fa1f04c7-f7ae-4844-a1c8-6958845777b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_W4&quot;)</value>
      <webElementGuid>2362f383-ae7f-475d-ad43-780679160e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_W4']</value>
      <webElementGuid>87853ad1-17cf-45b1-99fe-9f2c4f7c1ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_140']/tbody/tr/td/input</value>
      <webElementGuid>99eb14d7-ae89-4990-92ca-12a8ff8e9f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/div/div/div/form/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>df9361d4-a438-48d6-bfc2-235109107038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'idProd' and @id = 'isc_W4']</value>
      <webElementGuid>9a0b5987-da9e-4fd5-8184-a061e2ed9377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
