<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Supplier No.ContractPromotionRef.Orde_20ab08</name>
   <tag></tag>
   <elementGuidId>feba33f0-70bf-4b8c-8328-36d9bfd7d223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='isc_TA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_TA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_TA</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>a4e86242-2023-4bb1-9f41-163d55ffaf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>777c558f-a50b-40b8-87cd-078640a932c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_TA</value>
      <webElementGuid>aabd8cbb-1d5a-4326-9345-decbb6bd3531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellspacing</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1cab8ca-2557-4eca-9269-870336ea19a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellpadding</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>260a84d9-2966-48da-8704-f46fef6dae91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>937ee68e-3a07-4a30-884c-671ea4463178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supplier No.*:Contract :Promotion :Ref. :Order Branch :228 - DEMONSTRATION BRANCH 228Type :Purchase OrderDate Required :Shipping Basis :</value>
      <webElementGuid>b59de769-3a5f-43ef-9819-5d8e47ab82a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_TA&quot;)</value>
      <webElementGuid>d2d6d789-1b88-404a-bd72-eae12dafb9dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='isc_TA']</value>
      <webElementGuid>1a818115-deb1-4d23-82b4-6416a9444eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='isc_T9']/table</value>
      <webElementGuid>6d57ec06-acf7-45de-baa3-139cffc65ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::table[1]</value>
      <webElementGuid>ec080c2e-a304-43fd-b4c2-fc928ee6b419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/form/table</value>
      <webElementGuid>ca8739bc-2172-4233-8d57-9588cd50d075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[@id = 'isc_TA' and (text() = 'Supplier No.*:Contract :Promotion :Ref. :Order Branch :228 - DEMONSTRATION BRANCH 228Type :Purchase OrderDate Required :Shipping Basis :' or . = 'Supplier No.*:Contract :Promotion :Ref. :Order Branch :228 - DEMONSTRATION BRANCH 228Type :Purchase OrderDate Required :Shipping Basis :')]</value>
      <webElementGuid>529076b6-f4cd-4547-9e10-5f1c8a52d195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
