<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Desp. Method_isc_12D</name>
   <tag></tag>
   <elementGuidId>459d3c4d-054c-4e5c-a7ce-de73bbb5c7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_12D</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_12D']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Desp. Method&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a6ea493-45d3-4d3b-ab59-17251fad845a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_12D</value>
      <webElementGuid>15f2efa7-30db-48b6-83fb-4dc146960ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_7</value>
      <webElementGuid>bf9ac74a-8e9d-4b61-b41c-14acfabc5262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>e27ed0ca-7fbf-4c3d-8f28-497cfa83f21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>0a4ab64d-b18c-4c2a-a221-7881c85bc9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15552</value>
      <webElementGuid>1d6d45a9-c7f3-4c71-816d-0a452f7cced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>95dad432-6a1a-4ad1-9930-59fff1dffb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_12D&quot;)</value>
      <webElementGuid>36387437-3b87-4536-a36b-18b06d3fc793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_12D']</value>
      <webElementGuid>0901f31a-51f5-43b0-937b-a94da51260ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_12E']/tbody/tr/td/div</value>
      <webElementGuid>2904c2d4-cada-482b-86b4-a46aa2ec3472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/table/tbody/tr/td/div</value>
      <webElementGuid>8c31456e-ed6c-46ac-8e0d-b8a1984ee56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_12D']</value>
      <webElementGuid>f60af458-c62f-48b4-b5f2-3bb573530cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
