<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Desp. Method_isc_KQ</name>
   <tag></tag>
   <elementGuidId>ede33f12-b1c3-462e-a4ba-2f6345e5340a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_KQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='isc_KQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isc_KQ</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf56d9f1-86e4-4762-ab25-6f7f1f60e769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_KQ</value>
      <webElementGuid>b8c62236-6b26-4c4e-958f-3d7b494dfd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_SelectItem_10</value>
      <webElementGuid>fe5f1be2-8307-4c12-9ce3-6559ff70bb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9d</value>
      <webElementGuid>eb130562-7c25-47f2-b51b-450ffefd24bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectItemTextFocused</value>
      <webElementGuid>d1c67f69-b204-4444-be72-2b1404f7e967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10004</value>
      <webElementGuid>22ed5231-848a-45d3-9f65-54cc08cb87b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9d106034-4195-44d4-9c61-c840cce9b791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_KQ&quot;)</value>
      <webElementGuid>b5a9281e-f554-4655-8940-599f282bb4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='isc_KQ']</value>
      <webElementGuid>37e5a697-f852-46c7-9f17-8b925f7e95a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_KR']/tbody/tr/td/div</value>
      <webElementGuid>95ba5561-9735-4cdb-9920-5cfeaf8335b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/table/tbody/tr/td/div</value>
      <webElementGuid>e8aa0fed-ab06-49fb-adba-4901b11cc8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'isc_KQ']</value>
      <webElementGuid>64b8c004-f415-45d4-bd90-f5b3d9fd93ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
