<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Operator No_operatorId</name>
   <tag></tag>
   <elementGuidId>651c1b1d-6c26-4378-a017-45ae0cfe778b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_RK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_RK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Operator No&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bc2ffd6-0a26-4733-bb69-b56f84b66f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>9ff7e205-1261-4ecb-9d20-3c2d570e6598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operatorId</value>
      <webElementGuid>791aeb84-f837-4df7-a1d1-82144cd4680f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_RK</value>
      <webElementGuid>b01f8395-e8ad-4ff4-8786-a1cfe4911e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8caa4eed-0569-4f0f-a795-5861b260f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_60</value>
      <webElementGuid>388dba52-76da-4a79-beb8-57df89a2fd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>25963d37-38f8-4c9c-9b2f-5c8a6b466218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b11840da-1bed-402e-8d5e-a8db1bf8722c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_60._handleInput()</value>
      <webElementGuid>2e1a7b3c-f9d7-4cea-88b4-c8037f36f296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_60 == null) return;isc_TextItem_60.$1162()</value>
      <webElementGuid>ad9b7c7e-cd3e-4f32-aa50-a1deea81d3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>825e1885-e7e8-44d3-ae73-4e8d1c13050b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItemFocused</value>
      <webElementGuid>75ad1966-738b-4a55-b2ea-785929e5971b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11488</value>
      <webElementGuid>3b9e8512-44fb-4820-bada-08b8376f0d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_RK&quot;)</value>
      <webElementGuid>1bc50cdc-bd51-4db0-a8dd-b19ca5fc699f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_RK']</value>
      <webElementGuid>c0c8237d-10ca-467c-bece-bde5402abdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_RM']/input[2]</value>
      <webElementGuid>dc3d61a9-5bca-4a17-8290-90bd6e7ff54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>e90b6381-9df4-4b47-8aa4-a3572f785f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'operatorId' and @id = 'isc_RK']</value>
      <webElementGuid>7e46ef69-6255-42c1-a750-a38a466fcfc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
