<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tally_tallyText</name>
   <tag></tag>
   <elementGuidId>a3875ec5-9722-4148-8b09-8b1743e47ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_O3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'TEXT' and @name = 'tallyText']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_O3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tally&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92b1347f-98b9-40f4-9df1-979c531d00a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>1aabd451-07d8-4b48-baea-365ce39d68a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tallyText</value>
      <webElementGuid>7ba7979f-bc2d-4a62-b68a-1cc6c8d7c533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_O3</value>
      <webElementGuid>a5c261b3-9c6e-4d16-88ac-8b007bca1438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7b2ce6a-0bfb-487b-b66a-ed450116460d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_TextItem_43</value>
      <webElementGuid>09d31a4b-27e8-45ff-9f46-5717db26e565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>586da75d-7e65-4f44-86f3-a8c0a798d803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>262daec5-dc94-40d3-8874-05345b3da2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_TextItem_43._handleInput()</value>
      <webElementGuid>2f041531-7acc-459c-b1ab-9161618848ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_TextItem_43 == null) return;isc_TextItem_43.$1162()</value>
      <webElementGuid>1eb30b45-f4a8-402e-b7cf-90a306feb81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>251dfb2e-5c4b-4be5-91a7-ecf557a2b900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textItemFocused</value>
      <webElementGuid>e367d3e9-ccfd-4c64-93ae-48b0898714ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8867</value>
      <webElementGuid>8b415cf6-1afe-4a13-92c3-ad5d1b86ed5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_O3&quot;)</value>
      <webElementGuid>8e342991-1b77-4340-a6c0-95694b33e2d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_O3']</value>
      <webElementGuid>74695507-920d-4953-a745-ce1f9335fee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_O1']/input</value>
      <webElementGuid>b91b767a-5788-4598-ad4d-84ebe1fd1e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/form/table/tbody/tr[2]/td[7]/input</value>
      <webElementGuid>2624002d-8d85-438f-873b-451f7365816e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tallyText' and @id = 'isc_O3']</value>
      <webElementGuid>015fdd19-b4a6-4abb-a84b-158ac5877704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
