<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer_idCustX</name>
   <tag></tag>
   <elementGuidId>a2992ae0-ff79-4f4d-bd9f-decece047c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_IX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isc_IX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New Sales Order&quot;i >> internal:label=&quot;Customer&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddc90479-0cf1-4e52-a4e5-4dbf30638377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>7506ab13-10ae-4285-ba9c-a0a0048492b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idCustX</value>
      <webElementGuid>b5632293-bff3-4f49-b79b-5adc19e61af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_IX</value>
      <webElementGuid>b06579fa-3d3a-4e76-9227-e071f7224fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>handlenativeevents</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9342ae6a-8358-4c46-b305-da79649e83d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$89</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_3</value>
      <webElementGuid>f31cf67a-b3cb-4701-b1df-8659f04714a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>$9a</name>
      <type>Main</type>
      <value>$9b</value>
      <webElementGuid>245e0f5b-eed2-4c37-a244-d9695715b151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d722d25e-5bb9-44a8-8101-9a12cef6722f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>isc_ComboBoxItem_3._handleInput()</value>
      <webElementGuid>4857c670-697d-4601-93a1-d12e904cc1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselect</name>
      <type>Main</type>
      <value>if (window.isc_ComboBoxItem_3 == null) return;isc_ComboBoxItem_3.$1162()</value>
      <webElementGuid>e581b065-90a0-422f-adc7-9e275c972ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>OFF</value>
      <webElementGuid>66143715-d104-4661-bf6b-14b00e0270b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSuggestBoxFocused</value>
      <webElementGuid>62104396-ea5a-461e-9785-0e570d1a239b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9981</value>
      <webElementGuid>b57073c0-9b8c-40de-8671-023c0f419b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_IX&quot;)</value>
      <webElementGuid>2f9b3231-7021-4bd0-aabe-225f32f93d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isc_IX']</value>
      <webElementGuid>65a698a4-9d94-405b-b1e0-92e4829ab341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isc_QN']/input</value>
      <webElementGuid>2fe0344d-25c3-49fa-a649-4ecf4613bb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/input</value>
      <webElementGuid>ec141611-92e1-4e1b-81fb-245ba063e122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'idCustX' and @id = 'isc_IX']</value>
      <webElementGuid>8cf2e7d4-2fee-4538-9ec0-77ba81c360c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
