<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Customer</name>
   <tag></tag>
   <elementGuidId>a13eb95b-2714-4b00-83e1-3cc22cf808cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_IY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='isc_IY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New Sales Order&quot;i >> internal:text=&quot;Customer&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a0b56355-4cea-4a20-b008-bd2e87ae64d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_IY</value>
      <webElementGuid>7d8ce65f-bf79-41e1-aad3-a7b4a2122c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isc_IX</value>
      <webElementGuid>bc5dd5f6-7b26-49a2-94ee-0538d0e86bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer</value>
      <webElementGuid>c02b1552-3e0c-4728-a698-041e1aaca873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_IY&quot;)</value>
      <webElementGuid>a00fc867-aebb-4de2-9906-f180a6884eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='isc_IY']</value>
      <webElementGuid>9784574a-e93c-44a9-918e-46ba395eaa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='isc_IW']/nobr/label</value>
      <webElementGuid>18bbfb5d-bc86-4532-9055-1942da9d1787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Sale'])[1]/following::label[1]</value>
      <webElementGuid>4a36e4a1-2517-405c-917f-95bb74dcc4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lee Pearce'])[1]/preceding::label[1]</value>
      <webElementGuid>398e9a69-3d9b-4496-b919-dfeaa9be926b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Number'])[1]/preceding::label[1]</value>
      <webElementGuid>ae7facf5-3d3c-45fa-b1a7-215323f4de76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/nobr/label</value>
      <webElementGuid>f7a1d5e3-52ae-48dc-b7c0-4123e4b03b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'isc_IY' and (text() = 'Customer' or . = 'Customer')]</value>
      <webElementGuid>1504e736-b6fa-444d-8399-3da477a5b3c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
