<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Product</name>
   <tag></tag>
   <elementGuidId>8299a659-f58f-4d41-ada3-59d8183c33ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isc_17C</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Product&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3281a782-197b-43ab-bf73-f75b1292c17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_17C</value>
      <webElementGuid>d445ae95-a501-46fe-abc6-79d64ca75518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isc_17B</value>
      <webElementGuid>e67fde37-61da-45d4-a4e0-503b6d2a4120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>187e00e4-c493-424d-b403-a6fb4e0eeb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product</value>
      <webElementGuid>b3c72492-b867-4216-be4c-09c443793082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_17C&quot;)</value>
      <webElementGuid>0b6c1782-6dfd-4a5d-867c-d7aa1bbd4ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='isc_17C']</value>
      <webElementGuid>4ec7c9e4-ad48-473f-9fc4-3f164901ff36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='isc_17A']/nobr/label</value>
      <webElementGuid>44075d88-d333-4776-80e9-9de5ff2326cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Order'])[1]/following::label[1]</value>
      <webElementGuid>743ee1cf-1441-4a2c-8a75-080db3539a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[1]/following::label[1]</value>
      <webElementGuid>a816eec3-b6a1-431f-91fe-c79af8577c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::label[1]</value>
      <webElementGuid>0ad96ac6-230b-40ba-a25d-61038bc5c011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='roduct']/parent::*</value>
      <webElementGuid>9ff727c0-890e-4f36-8955-98e838fcc5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/nobr/label</value>
      <webElementGuid>31a7a07d-1b19-43fd-9264-660f9ffd5038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'isc_17C' and (text() = 'Product' or . = 'Product')]</value>
      <webElementGuid>6b746d2d-a9d5-4392-bff8-c136268aa819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
