<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Delivery Area_searchIcon</name>
   <tag></tag>
   <elementGuidId>3f97b1ff-bdfa-4f64-9795-a21fb7bdd084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'http://frameworks.cairnshardware.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/search_icon.png')])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isc_11U</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Delivery area is mandatory Delivery Area&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8b489534-6dcb-4d47-8a5a-834330c832f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frameworks.cairnshardware.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/search_icon.png</value>
      <webElementGuid>bcc8c64e-fd78-457f-a29b-e9262488c6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>44c21529-8e95-4d64-b1fc-d289dd2613bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>9a435557-de1d-4d8a-9b02-d8f4c1636750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>b5de8358-f0a8-4653-b8f0-a371ecb93c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isc_11U</value>
      <webElementGuid>f17f94d3-c4de-42ce-b642-a661101c9285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb57ce4e-2798-4170-b440-d667f33e76ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>suppress</name>
      <type>Main</type>
      <value>TRUE</value>
      <webElementGuid>cc68c0c0-ec7f-4ca1-a84e-1bc3dcd3383e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39f76f9f-3b2f-4524-997e-ecf39db1b9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_11U&quot;)</value>
      <webElementGuid>3f85b172-c1d2-49d9-899b-7a03c0e01985</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='isc_11U']</value>
      <webElementGuid>4001984d-c372-41d6-8c16-025f0b2d9b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='isc_11T']/img</value>
      <webElementGuid>3cb1c87f-f21e-4853-b8fd-678a31b8b850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'http://frameworks.cairnshardware.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/search_icon.png')])[9]</value>
      <webElementGuid>9abdc62a-b78c-40f9-b512-3867ab7b52c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/div/table/tbody/tr/td/span/img</value>
      <webElementGuid>54c78678-b2ba-473d-a1e9-ca36072f5465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://frameworks.cairnshardware.com.au:8080/FWDemo/frameworks/sc/skins/Frameworks7/images/custom/buttons/search_icon.png' and @id = 'isc_11U']</value>
      <webElementGuid>097264aa-df8f-4b5d-8f27-6a99e4b2b1df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
