<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Picked_Qty_row1</name>
   <tag></tag>
   <elementGuidId>682e3ce9-5851-403c-8f58-15d3c59b8800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[8]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;0.0000&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>23a08a36-e6ae-4239-8b3e-d4a95cfad79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>50c99497-defa-42f8-b7f4-71fea01ee7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cellclipdiv</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a383401c-4e6d-4651-90fa-dd3e4a7bb22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0000</value>
      <webElementGuid>377f0381-e3ab-44e2-a458-3ee27d7430ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isc_1DOtable&quot;)/tbody[1]/tr[1]/td[@class=&quot;treeTallCellSelectedOver&quot;]/div[1]</value>
      <webElementGuid>fa19259a-ebb8-44a8-8800-266dfb99ce36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='isc_1DOtable']/tbody/tr/td[8]/div</value>
      <webElementGuid>cc15eca7-b40b-4000-bda1-8f9ece35496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EA'])[1]/following::div[2]</value>
      <webElementGuid>89ba87b9-a5c7-4da2-a39d-291899d40b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TURPENTINE 1LT DIGGERS 16010-1DIG RECOCHEM'])[1]/following::div[5]</value>
      <webElementGuid>53dde071-9b20-451d-aa58-b03333bda301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line'])[1]/preceding::div[5]</value>
      <webElementGuid>7c1aaaa7-2339-4dc0-88d6-a9b2d1499f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/preceding::div[9]</value>
      <webElementGuid>e2dbe91a-b7ba-4adb-a4c1-27d253838ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.0000']/parent::*</value>
      <webElementGuid>30264c8a-1fec-46c5-a6f9-cf04d96a649f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[8]/div</value>
      <webElementGuid>7abfcfc4-30d8-41ac-bac2-5809e019bddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.0000' or . = '0.0000')]</value>
      <webElementGuid>5a452f07-2a1e-461b-87c2-1f6dfbf2fc8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
